--[[
	LFG MatchMaker - Addon for World of Warcraft.
	URL: https://github.com/dlicudi/LFG_MatchMaker
	Copyright (C) 2019-2020 L.I.R.

	This file is part of 'LFG MatchMaker' addon for World of Warcraft.

    'LFG MatchMaker' is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    'LFG MatchMaker' is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with 'LFG MatchMaker'. If not, see <https://www.gnu.org/licenses/>.
]]--


------------------------------------------------------------------------------------------------------------------------
-- MESSAGE TYPE IDENTIFIERS
------------------------------------------------------------------------------------------------------------------------


LFGMM_GLOBAL.MESSAGETYPE_IDENTIFIERS = {
	EN = {
		{
			Type = "LFG",
			Identifiers = {
				"lfg",
				"lf[%W]*group",
				"looking[%W]*for[%W]*group",
				"dps[%W]*lf",
				"tank[%W]*lf",
				"heal[e]?[r]?[%W]*lf",
				"dps[%W]*looking[%W]*for",
				"tank[%W]*looking[%W]*for",
				"heal[e]?[r]?[%W]*looking[%W]*for",
				"pri[e]?st[%W]*lf",
				"warr[i]?[o]?[r]?[%W]*lf",
				"mage[%W]*lf",
				"[w]?[a]?[r]?lock[%W]*lf",
				"shaman[%W]*lf",
				"pala[d]?[i]?[n]?[%W]*lf",
				"hunt[e]?[r]?[%W]*lf",
				"ro[u]?g[u]?e[%W]*lf",
				"druid[%W]*lf",
				"pri[e]?st[%W]*looking[%W]*for",
				"warr[i]?[o]?[r]?[%W]*looking[%W]*for",
				"mage[%W]*looking[%W]*for",
				"[w]?[a]?[r]?lock[%W]*looking[%W]*for",
				"shaman[%W]*looking[%W]*for",
				"pala[d]?[i]?[n]?[%W]*looking[%W]*for",
				"hunt[e]?[r]?[%W]*looking[%W]*for",
				"ro[u]?g[u]?e[%W]*looking[%W]*for",
				"druid[%W]*looking[%W]*for",
			}
		},
		{
			Type = "LFM",
			Identifiers = {
				"lf[%W]*[%d]+",
				"lf[%W]*[%d]*[%W]*m",
				"lf[%W]*[%d]*[ax]?[%W]*dps",
				"lf[%W]*[%d]*[ax]?[%W]*tank",
				"lf[%W]*[%d]*[ax]?[%W]*heal",
				"lf[%W]*[%d]*[ax]?[%W]*dd",
				"lf[%W]*[%d]*[ax]?[%W]*caster",
				"lf[%W]*[%d]*[ax]?[%W]*mele",
				"lf[%W]*[%d]*[ax]?[%W]*range",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*dps",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*tank",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*heal",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*dd",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*caster",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*mele",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*range",
				"lf[%W]*[%d]*[ax]?[%W]*pri[e]?st",
				"lf[%W]*[%d]*[ax]?[%W]*warr",
				"lf[%W]*[%d]*[ax]?[%W]*mage",
				"lf[%W]*[%d]*[ax]?[%W]*[w]?[a]?[r]?lock",
				"lf[%W]*[%d]*[ax]?[%W]*shaman",
				"lf[%W]*[%d]*[ax]?[%W]*pala",
				"lf[%W]*[%d]*[ax]?[%W]*hunt",
				"lf[%W]*[%d]*[ax]?[%W]*ro[u]?g[u]?e",
				"lf[%W]*[%d]*[ax]?[%W]*druid",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*pri[e]?st",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*warr",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*mage",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*[w]?[a]?[r]?lock",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*shaman",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*pala",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*hunt",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*ro[u]?g[u]?e",
				"looking[%W]*for[%W]*[%d]*[ax]?[%W]*druid",
				"need[%W]*one[%W]*more",
				"need[%W]*[%d]+[%W]*more",
				"need[%W]*[%d]*[%W]*dps",
				"need[%W]*[%d]*[%W]*tank",
				"need[%W]*[%d]*[%W]*heal",
				"need[%W]*[%d]*[%W]*dd",
				"need[%W]*[%d]*[%W]*caster",
				"need[%W]*[%d]*[%W]*mele",
				"need[%W]*[%d]*[%W]*range",
				"seek[%W]*one[%W]*more",
				"seek[%W]*[%d]+[%W]*more",
				"seek[%W]*[%d]+[%W]*more",
				"seek[%W]*[%d]*[%W]*dps",
				"seek[%W]*[%d]*[%W]*tank",
				"seek[%W]*[%d]*[%W]*heal",
				"seek[%W]*[%d]*[%W]*dd",
				"seek[%W]*[%d]*[%W]*caster",
				"seek[%W]*[%d]*[%W]*mele",
				"seek[%W]*[%d]*[%W]*range",
				"last[%W]*dps",
				"last[%W]*tank",
				"last[%W]*heal",
				"last[%W]*spot",
				"any[%W]*dps[%W]*for",
				"any[%W]*tank[%W]*for",
				"any[%W]*heal[e]?[r]?[%W]*for",
			}
		}
	},
	-- DE = {},
	FR = {
		{
			Type = "LFG",
			Identifiers = {
				"[%d][%d][%W]*dispo[n]?[i]?[b]?[l]?[e]?",
				"[%d][%d][%W]*cherch[e]?[o]?[n]?[s]?",
				"[%d][%d][%W]*up[%W]*pour",
				"[%d][%d][%W]*dps[%W]*pour",
				"[%d][%d][%W]*tank[%W]*pour",
				"[%d][%d][%W]*heal[e]?[r]?[%W]*pour",
				"[%d][%d][%W]*soigneur[%W]*pour",
				"cherch[e]?[o]?[n]?[s]?[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*g[r]?oupe",
				"cherch[e]?[o]?[n]?[s]?[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*grp",
			}
		},
		{
			Type = "LFM",
			Identifiers = {
				"un[%W]*dps[%W]*[d]?[e]?[%W]*dispo[n]?[i]?[b]?[l]?[e]?[%W]*pour",
				"un[%W]*tank[%W]*[d]?[e]?[%W]*dispo[n]?[i]?[b]?[l]?[e]?[%W]*pour",
				"un[%W]*heal[e]?[r]?[%W]*[d]?[e]?[%W]*dispo[n]?[i]?[b]?[l]?[e]?[%W]*pour",
				"un[%W]*soigneur[%W]*[d]?[e]?[%W]*dispo[n]?[i]?[b]?[l]?[e]?[%W]*pour",
				"un[%W]*dps[%W]*up[%W]*pour",
				"un[%W]*tank[%W]*up[%W]*pour",
				"un[%W]*heal[e]?[r]?[%W]*up[%W]*pour",
				"un[%W]*soigneur[%W]*up[%W]*pour",
				"un[%W]*dps[%W]*pour",
				"un[%W]*tank[%W]*pour",
				"un[%W]*heal[e]?[r]?[%W]*pour",
				"un[%W]*soigneur[%W]*pour",
				"un[%W]*dps[%W]*et",
				"un[%W]*tank[%W]*et",
				"un[%W]*heal[e]?[r]?[%W]*et",
				"un[%W]*soigneur[%W]*et",
				"un[%W]*dps[%W]*ou",
				"un[%W]*tank[%W]*ou",
				"un[%W]*heal[e]?[r]?[%W]*ou",
				"un[%W]*soigneur[%W]*ou",
				"un[%W]*dps[%W]*un",
				"un[%W]*tank[%W]*un",
				"un[%W]*heal[e]?[r]?[%W]*un",
				"un[%W]*soigneur[%W]*un",
				"un[%W]*petit[%W]*dps",
				"un[%W]*petit[%W]*tank",
				"un[%W]*petit[%W]*heal",
				"un[%W]*petit[%W]*soigneur",
				"deux[%W]*dps[%W]*pour",
				"deux[%W]*dps[%W]*et",
				"deux[%W]*dps[%W]*ou",
				"deux[%W]*petit[%W]*dps",
				"[%d][%W]*petit[%W]*dps",
				"[%d][%W]*petit[%W]*tank",
				"[%d][%W]*petit[%W]*heal",
				"[%d][%W]*petit[%W]*soigneur",
				"[%d][%W]*dps[%W]*pour",
				"[%d][%W]*tank[%W]*pour",
				"[%d][%W]*heal[e]?[r]?[%W]*pour",
				"[%d][%W]*soigneur[%W]*pour",
				"[%d][%W]*dps[%W]*et",
				"[%d][%W]*tank[%W]*et",
				"[%d][%W]*heal[e]?[r]?[%W]*et",
				"[%d][%W]*soigneur[%W]*et",
				"[%d][%W]*dps[%W]*ou",
				"[%d][%W]*tank[%W]*ou",
				"[%d][%W]*heal[e]?[r]?[%W]*ou",
				"[%d][%W]*soigneur[%W]*ou",
				"besoin[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*dps",
				"besoin[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*tank",
				"besoin[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*heal",
				"besoin[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*soigneur",
				"cherch[e]?[o]?[n]?[s]?[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*dps",
				"cherch[e]?[o]?[n]?[s]?[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*tank",
				"cherch[e]?[o]?[n]?[s]?[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*heal",
				"cherch[e]?[o]?[n]?[s]?[%W]*[d]?[%W]*[u]?[n]?[%d]*[%W]*soigneur",
				"encore[%W]*un[%W]*dps",
				"encore[%W]*un[%W]*tank",
				"encore[%W]*un[%W]*heal",
				"encore[%W]*un[%W]*soigneur",
				"encore[%W]*un[%W]*place",
				"dernier[e]?[%W]*dps",
				"dernier[e]?[%W]*tank",
				"dernier[e]?[%W]*heal",
				"dernier[e]?[%W]*soigneur",
				"dernier[e]?[%W]*place",
				"dernier[e]?[%W]*person",
				"manque[%W]*[u]?[n]?[%d]*[%W]*dps",
				"manque[%W]*[u]?[n]?[%d]*[%W]*tank",
				"manque[%W]*[u]?[n]?[%d]*[%W]*heal",
				"manque[%W]*[u]?[n]?[%d]*[%W]*soigneur",
				"manque[%W]*[u]?[n]?[%d]*[%W]*person",
				"dps[%W]*demande",
				"tank[%W]*demande",
				"heal[%W]*demande",
				"soigneur[%W]*demande",
				"reste[%W]*[%d]+[%W]*place[s]?[%W]*pour",
				"de[%W]*tout[%W]*pour",
				"last[%W]*pour",
				"recrute[%W]*pour",
				"monte[%W]*g[r]?oupe",
				"monte[%W]*grp",
				"[%W]+et[t]?[%W]*go[%W]+",
				"[%W]+et[t]?[%W]*go$",
			}
		},
		{
			Type = "LFG",
			Identifiers = {
				"dps[%W]*up[%W]*pour",
				"tank[%W]*up[%W]*pour",
				"heal[e]?[r]?[%W]*up[%W]*pour",
				"soigneur[%W]*up[%W]*pour",
				"dispo[n]?[i]?[b]?[l]?[e]?[%W]+",
				"dispo[n]?[i]?[b]?[l]?[e]?$",
			}
		},
	},
	-- ES = {},
	-- RU = {},
};